language: java
jdk: oraclejdk8

before_install:
- rm -rf /home/travis/build/garashis/MySpringBoot/

install: true
script: mvn install

after_success:
- pwd

- mkdir $HOME/buildApk/
- ls -l
- cd $HOME/buildApk/
- pwd
- ls -l
- git config --global user.email "ashishg.garg@gmail.com"
- git config --global user.name "Ashish Garg"
- git clone --depth=50 --branch=master https://github.com/garashis/MySpringBoot.git
- cd MySpringBook
- mkdir target
- ls -l
- cp -r /home/travis/build/garashis/MySpringBoot/target/MySpringBoot-0.0.1-SNAPSHOT.jar $HOME/buildApk/MySpringBoot/target/
- ls -l
- git add -f .
- git remote rm origin
- git remote add origin https://garashis:$GITHUB_API_KEY@github.com/garashis/MySpringBoot.git
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed [skip ci] "
- git push -fq origin master
- echo -e "Done with magic\n"